In [2]:
import numpy as np

### array ()

In [2]:
listOfNumber  = [13,23,21,22,5,56,89]
arrayOfNumber  = np.array(listOfNumber)
print(type(arrayOfNumber))

<class 'numpy.ndarray'>


In [ ]:
np.int8 ; ###   -128 to 127
np.uint8 ;  ### np.int8  *2
np.int16;  ### -32,768 to 32,767
np.uint16 ; ###  np.int16 *2
np.int32; ###  -2,147,483,648  to  2,147,483,647
np.uint32 ; ### np.int32 *2
np.int64 ; ### -9,223,372,036,854,775,808  to  9,223,372,036,854,775,807
np.uint64 ; ### np.int64 *2
np.int_ ; ### look like np.int64  (basic int in python )
### ----------------------------------------------------------------------------------------------------------
np.float16 ; 
np.float32 ; 
np.float96 ; 
np.float128 ; 
### ----------------------------------------------------------------------------------------------------------
np.bool_ ; 
### ----------------------------------------------------------------------------------------------------------


##### flexibility (upcasting) 

In [4]:
arr1  = np.array(["python" , 12, 22 , 13 , 15.5 ])
print(arr1)

['python' '12' '22' '13' '15.5']


##### .dtype

In [6]:
arr1  = np.array(["python" , 12, -22 , 13 , 15.5 ])
print(arr1.dtype)

<U32


##### astype()    or dtype = ...

In [8]:
arr2  = np.array([12,23,13,14]).astype(np.int8)
print(arr2.dtype)

int8


In [ ]:
arr2  = np.array([12,23,13,14] , dtype= np.int8)
print(arr2.dtype)

int8


##### string 

In [ ]:
arr3 = np.array(["python1234" , "amir"]  , dtype= "S3")  ## or "U4"
print(arr3.dtype)
print(arr3)

## U ==> ascii  + not ascii 
## S ==> not ascii 

|S3
[b'pyt' b'ami']


### .shape  ,   .ndim

In [32]:
#0d 
arr_0d = np.array(10)
print(arr_0d)
print(arr_0d.shape)
print(arr_0d.ndim)

10
()
0


In [33]:
#1d 
arr_1d = np.array([12,13,14] , dtype= "i1")
print(arr_1d)
print(arr_1d.shape)
print(arr_1d.ndim)

[12 13 14]
(3,)
1


In [ ]:
#2d (matrix)
arr_2d = np.array([[12,13,14],
                                [20 ,23, 22]] ,  dtype="i1")
print(arr_2d)
print(arr_2d.shape)
print(arr_2d.ndim)

[[12 13 14]
 [20 23 22]]
(2, 3)
2


In [35]:
#3d 
arr_3d = np.array([
    [[1], [2], [3]],
    [[4], [5], [6]]
] ,  dtype="i1")
print(arr_3d)
print(arr_3d.shape)
print(arr_3d.ndim)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
(2, 3, 1)
3


### flatten()  , order  = ("C" or "F" )

In [36]:
arr1 = np.array([ [39,20] , [3,12] ] , order = "C")
arr2 = np.array([ [39,20] , [3,12] ] , order = "F")
print(arr1)
print(arr2) 

[[39 20]
 [ 3 12]]
[[39 20]
 [ 3 12]]


In [38]:
arr1 = arr1.flatten(order="C") 
arr2  = arr2.flatten(order = "F")
print(arr1)   
print(arr2) 

# "C"  ==>  reading by row 
# "F"  ==> reading by column 

[39 20  3 12]
[39  3 20 12]


### indexing (reading)

In [39]:
#1d 
arr_1d = np.array([12,13,14] , dtype= "i1")
print(arr_1d[1])

13


In [44]:
#2d (matrix)
arr_2d = np.array([[12,13,14],
                                [20 ,23, 22]] ,  dtype="i1")

print(arr_2d[1,0])
print(arr_2d[1][0])

20
20


In [48]:
#3d 
arr_3d = np.array([
    [[1], [2], [3]],
    [[4], [5], [6]]
] ,  dtype="i1")

print(arr_3d[1,2,0])
print(arr_3d[1][2][0])

6
6


### slicing 

In [49]:
#1d 
arr_1d = np.array([12,13,14 , 15 ,16, 17] , dtype= "i1")
print(arr_1d[1:5])

[13 14 15 16]


In [54]:
#2d (matrix)
arr_2d = np.array([[1, 2, 3] ,
                                 [4, 5, 6] , 
                                 [7, 8, 9]] ,  dtype="i1")

print(arr_2d[0:2])
print(arr_2d[:2 , 1:3])
print(arr_2d[: , 1:3])
print(arr_2d[: , 1])

[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]
[[2 3]
 [5 6]
 [8 9]]
[2 5 8]


In [56]:
#3d 
arr_3d = np.array([[[1 ,2 ,3] , [4, 5, 6]] , [[7, 8, 9] , [10, 11, 12]]] ,  dtype="i1")

print(arr_3d[: , 0 , 2])

[3 9]


### filtering  +  where

In [35]:
arr_1d = np.array([20, 30, 40, 50] ,  dtype="i1")
arr_1_1d = np.array([25,2, 24, 60] , dtype= "i1")
arr2 = np.array([True , False , True , False])
arr3  = arr_1d[arr2]
print(arr3)

resalt = arr_1d > 30 ##  filtering type one 
print(resalt)

print( arr_1d[arr_1d> 30])  ## filtering type two 

arr3  = arr_1d[arr_1d != 40]  ## removing with filter 
print(arr3)

result1 = np.where(arr_1d > 30)       ## return insex of arr_1d !!
print(result1)

result2 = np.where(arr_1d > 30 , 10 , -1)  ##  if the condition is true ==> 10 , if it's false ==> -1
print(result2)

result3  = np.where(arr_1d > arr_1_1d , arr_1d , 0 )  
print(result3)

###   in metrix  2*2  we give to array in output :  row and column 



[20 40]
[False False  True  True]
[40 50]
[20 30 50]
(array([2, 3]),)
[-1 -1 10 10]
[ 0 30 40  0]


In [3]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array( [ [2], [5] ] )
print(arr1 + arr2)

[[3 4]
 [8 9]]


In [ ]:
m1  = np.array([[1, 2, 3], 
                            [4, 5, 6], 
                            [7, 8, 9]] , dtype="i1")
sum_data = np.sum(m1)                ## sum  all data in m1 
print(f"all data : {sum_data}")
sum_columns = np.sum(m1 , axis=0)          ## sum data by columns ==> axis =0
print(f"columns : {sum_columns}")
sum_rows = np.sum(m1 , axis=1)                ## sum data by rows ==>  axis = 1
print(f"rows : {sum_rows}")


all data : 45
columns : [12 15 18]
rows : [ 6 15 24]


### broadcasting 

In [13]:
m1  = np.array([0,1,2,3])
m2  = np.array([1,2,3])
m3 = m1 + m2 [: , np.newaxis]     ## convert rows to columns !! 
print(m3)


[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


## vectorize 

###### we can use fuction in my array with **vectorize** 

##### example 1 :

In [18]:
def vectorize_function(x) :
    if x >= 0 :
        return x**2
    else :
        return abs(x)

In [19]:
arr1 = np.array([3, -4 , -5 , 12 , 1,  0 ])
vectorized_function = np.vectorize(vectorize_function)
result  = vectorized_function(arr1)
print(result)


[  9   4   5 144   1   0]


##### example 2 :

In [20]:
def compare (p1 , p2) :
    if p2 > p1 :
        return "inc"
    elif p2 < p1 :
        return "dec"
    else :
        return "unchange"

In [22]:
last_year  = np.array([150 , 200 , 300 , 400 , 500])
this_year  = np.array([100 , 150 , 300 , 450 , 520])

In [23]:
compare_prices = np.vectorize(compare)
result  = compare_prices(last_year , this_year) 
print(result)

['dec' 'dec' 'unchange' 'inc' 'inc']


### all()  ,  any()

In [ ]:
arr1 = np.array([12, 23, 14, 30])
result = np.all(arr1 > 20)   ##  what's going on in () ==> res =  arr1 > 20 ==> [false ,  true ,  false ,  true]
result2  =  np.any(arr1 >20)
print(result)
print(result2)

False
True


### copy and view 

In [ ]:
orginal_arr = np.array([2, 3, 4, 5])
copied_arr = orginal_arr. copy()
orginal_arr[0] = 300
print (orginal_arr)
print(copied_arr)

[300   3   4   5]
[2 3 4 5]


In [4]:
orginal_arr = np.array([2, 3, 4, 5])
viewed_arr = orginal_arr.view()
orginal_arr[0] = 300
print(orginal_arr)
print(viewed_arr)

[300   3   4   5]
[300   3   4   5]


## methods in numpy 

In [3]:
arr1  = np.array([1,2,3])
arr2 = np.zeros((2,2))
arr3  = np.ones((3,3))
arr4  = np.full((2,2), 8)
arr5  = np.eye(3)             ## scaller metrix  n*n
arr6 = np.arange(1, 12 , 2 )    ##  look like the range in python 
arr7 = np.arange(6).reshape((2,3))   ## make a new shape in metrix 
arr8 = np.linspace(0, 1 , 5)     ##  devide the same part 
arr9 = np.split(arr6 , 3 )   ##  make a partision (efraz)
arr10 = np.array([13 ,13 ,13, 22, 22, 69 ])
arr10 = np.unique(arr10 , return_counts= True)
arr11 = np.vstack((arr1 , arr7))     ##  1*3  + 2*3 = 3*3
arr12 = np.hstack((arr6 , arr1 ))    ##  [....] + [....] =  [............]
print(arr7)


[[0 1 2]
 [3 4 5]]


### .npy 

######  for saving : 

In [38]:
my_array  = np.array([2,3,5,10])
np.save("test.npy" , my_array)

###### for loading : 

In [37]:
my_arr = np.load("test.npy" )
print(my_arr)

[ 2  3  5 10]


### random 

In [ ]:
import numpy as np
rand1 = np.random.randint(1,50, size= (4,4)) ### very important for you !!!
print(rand1)
print("\n\n")
rand2 = np.random.randint(1,50 , size= (4,4))
print(rand2) 
print("\n\n")


sum_value = rand1+rand2
print(sum_value)
print("\n\n")
filter_rand = np.where(sum_value >50 , sum_value , 0 )
print(filter_rand)
print("\n\n")
filter_rand = filter_rand[filter_rand != 0]
print(f"filter rand {filter_rand}")
print("\n\n")


[[12 23 18  3]
 [26 17 35  3]
 [47 25  9 43]
 [26  2 37 13]]



[[41 49 26 38]
 [10 28 32  1]
 [33 22 46  2]
 [17 14 43 48]]



[[53 72 44 41]
 [36 45 67  4]
 [80 47 55 45]
 [43 16 80 61]]



[[53 72  0  0]
 [ 0  0 67  0]
 [80  0 55  0]
 [ 0  0 80 61]]



filter rand [53 72 67 80 55 80 61]





## example : 


In [62]:
matrix  =  np.arange(1,10).reshape(3,3)

##### find the location of max value of matrix

In [63]:
max_value  = matrix.max()
##np.unravel_index :
##  in index of the  flatten  array ,  the number is frome where ?  output ==> row() , column()
### argmax : 
### find the max number and then make it  position to flatten array !!   output==> index of flatten array 
indexer  = np.unravel_index(np.argmax(matrix) , matrix.shape)

print(indexer)
print(matrix[indexer])

(np.int64(2), np.int64(2))
9
